APP_SECRET_KEY = 'Oib[~L:pA&#]yO#uOf%pfw:Zw~KPL)nD5oMA*q|i(Qx4Xms7X/jp6Wt2^f6tO85FDJl[#rp7#!7g]yVj#z)hTSqxi,Sopw0TpTq[O*Js15jL)F]q0rZ4IwjqAjo{]4Np'

import random
APP_SECRET_KEY = str(random.getrandbits(64))

PRODUCTION_SERVER = False

DATABASE_HOST = 'localhost'

DATABASE_NAME = 'db'

DATABASE_USER = 'root'

DATABASE_PASSWORD = 'password'

BAN_TIME_IP = 300

BAN_TIME_ACCOUNT = 150

MAX_LOGIN_ATTEMPTS_IP = 30

MAX_LOGIN_ATTEMPTS_ACCOUNT = 15

PERMISSION_DEFAULT = 0

PERMISSION_REGISTERED = 10

PERMISSION_ACTIVATED = 20

PERMISSION_ADMIN = 200

PERMISSION_WEBMASTER = 255
